name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Lint
        run: ./gradlew app:lint
      - name: Lint Results
        uses: yutailang0119/action-android-lint@v3.1.0
        with:
          report-path: app/build/reports/lint/report.xml
      - name: jvm tests
        run: ./gradlew test
      - name: Unit Test Coverage Reports
        run: ./gradlew app:jacocoTestReport
      - uses: actions/upload-artifact@v3
        name: Store Reporting Artifacts
        if: failure()
        with:
          name: app-reports
          path: |
            app/build/reports
            app/build/outputs