name: Deploy App

# only deploy a release if we pass the other tests: https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions
on:
  workflow_run:
    workflows: [ "Android CI" ]
    branches: [ main ]
    types:
      - completed
    status:
      - success
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Assemble Release
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: ./gradlew assembleRelease

      - name: Export environment variables
        run: |
          echo "::set-env name=VERSION_NAME::$(cat app/build/outputs/app_versioning/release/version_name.txt)"
          echo "::set-env name=VERSION_CODE::$(cat app/build/outputs/app_versioning/release/version_code.txt)"

      - name: Publish Release
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: ./gradlew publishAllPublicationsToGithubPackagesRepository